config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: :show

  resources :groups do
    member do
      get 'add_user'
      post 'store_user'
      delete 'remove_user'
    end

    resources :activities, only: :new
  end
  
  resources :activities do
    member do
      post 'vote'
      post 'definitive'
	  get 'search_photo'
	  post 'choose_photo'
	  post 'store_photo_url'
    end
  end

  match '/tweet' => 'twitter#tweet', via: :all

  root :to => 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true, length: { in: 6..30 }
  validates :hometown, presence: true, length: { in: 3..30 }

  belongs_to :owner, class_name: 'User'
  has_and_belongs_to_many :user
  has_many :activity, :dependent => :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  # Check URL below for Devise's helper methods for eg. authentication etc.
  # https://github.com/plataformatec/devise#controller-filters-and-helpers
  
  before_filter :require_owner, only: [:destroy, :edit, :update, :add_user, :store_user, :remove_user]
  
  helper_method :current_user_is_owner

  def index
    @title = 'Meetup groups'
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def new
	  @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.user << current_user
    if @group.save
      redirect_to @group
    else
      render 'new'
    end
  end

  def edit
	  @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end
  
  def add_user
	  @group = Group.find(params[:id])
  end
  
  def store_user
    if member = User.find_by_email(add_user_params[:email])
      @group.user << member unless @group.user.include?(member)
      redirect_to @group
    else
      @group.errors.add(:email, " provided is not a valid user.")
      render 'add_user'
    end
  end
  
  def remove_user
    member = User.find(params[:user_param])
    if member.id != @group.owner_id
      @group.user.destroy(member)
    end
    redirect_to @group
  end
  
  def current_user_is_owner
	  return @group.owner == current_user
  end

  private
    def group_params
      params.require(:group).permit(:name, :hometown)
    end

    def add_user_params
      params.require(:user).permit(:email)
    end

    def require_owner
      @group = Group.find(params[:id])
      if current_user.id != @group.owner_id
        redirect_to @group
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, html: {'novalidate' => 'true'} do |f| %>
  <% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited
      this group from being saved:</h2>
    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
	<%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :hometown %><br>
    <%= f.text_field :hometown %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/groups/add_user.html.erb
<h1>Add an user to your group</h1>

<%= form_for :user, :url => {:action => "store_user"}, html: {'novalidate' => 'true'} do |f| %>
  <% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited
      this user from being added to the group:</h2>
    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
	<%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', group_path(@group) %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form' %>
 
<%= link_to 'Back', group_path(@group) %>

app/views/groups/index.html.erb
<h1><%= @title %></h1>

<% if @groups.exists? %>
    <% @groups.each do |group| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to group.name, group_path(group) %>
          <% if group.owner == current_user %>
            <small class="pull-right">
              <%= link_to 'Delete', group_path(group),
                          method: :delete, data: { confirm: 'Are you sure?' } %>
            </small>
          <% end %>
        </div>
        <ul class="list-group">
          <li class="list-group-item"><small>Location:</small> <%= group.hometown %></li>
          <li class="list-group-item"><small>Group Owner:</small> <%= group.owner.email %></li>
        </ul>
      </div>
    <% end %>
<% else %>
    <h2>No groups were found</h2>
<% end %>

<%= link_to 'Create a new group', new_group_path %>

app/views/groups/my_meetups.html.erb
<!--TODO: Doesn't belong here to be moved in user views directory-->

<h1>My Meetups</h1>
<br/>
<h2>Created meetups</h2>
<br/>
<h2>Meetups I am participating</h2>
<br/>

<%= link_to 'Create a new group', new_group_path %>

app/views/groups/new.html.erb
<h1>Create a new Meetup Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @group.name %>
      <% if current_user_is_owner %>
        <small class="pull-right">
          <%= link_to 'Edit', edit_group_path(@group) %> |
          <%= link_to 'Delete',
                      group_path(@group),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </small>
      <% end %>
  </div>

  <ul class="list-group">
    <li class="list-group-item">Owner: <%= @group.owner.email %></li>
    <li class="list-group-item">Hometown: <%= @group.hometown %></li>
    <li class="list-group-item">Created on: <%= @group.created_at.to_formatted_s(:short) %></li>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    Members

    <% if current_user_is_owner %>
      <small class="pull-right">
        <%= link_to 'Add a member', add_user_group_path %>
      </small>
    <% end %>
  </div>

  <ul class="list-group">
    <% if @group.user.exists? %>
      <% @group.user.each do |user| %>
          <li class="list-group-item"><%= link_to user.email, user_path(user) %>
        <% if current_user_is_owner && user != current_user %>
          <small class="pull-right">
            <%= link_to 'Remove', remove_user_group_path(user_param: user),
                        method: :delete, data: { confirm: 'Are you sure?' } %>
          </small>
        <% end %></li>
      <% end %>
    <% else %>
      <li class="list-group-item"><small>There are currently no members in this group.</small></li>
    <% end %>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    Activities
    <small class="pull-right">
      <% if current_user_is_owner %>
        <%= link_to 'Add an activity', new_group_activity_path(group_id: @group) %>
      <% end %>
    </small>
  </div>
  <% if @group.activity.exists? %>
    <table class="table">
      <tr>
        <th>Activity</th>
        <th>Time</th>
        <th>Location</th>
        <th>Votes</th>
        <th>Definitive</th>
        <% if current_user_is_owner %>
          <th>Delete</th>
        <% end %>
      </tr>
      <% activities = @group.activity.sort_by { |act| act.voters.count }.reverse %>
      <% activities.each do |activity| %>
        <tr>
            <td><strong><%= link_to activity.name, activity_path(activity) %></strong></td>
            <td><%= activity.start_date.to_formatted_s(:short) %></td>
            <td><%= activity.location %></td>
            <td>
              <%= activity.voters.count.to_s %>
              <% if @group.user.include?(current_user) %>
                <% if activity.voters.include? current_user %>
                  <i class="fa fa-fw fa-thumbs-o-up" style="color: grey;"></i>
                <% else %>
                  <%= link_to '<i class="fa fa-fw fa-thumbs-o-up"></i> +1'.html_safe, vote_activity_path(activity), method: :post %>
                <% end %>
               <% end %>
            </td>
            <td>
              <%= activity.definitive ? 'Yes' : 'No'%>
              <% if current_user_is_owner && ! activity.definitive%>
                <%= link_to '<i class="fa fa-fw fa-check"></i> Mark as definitive'.html_safe, definitive_activity_path(activity), method: :post %>
              <% end %>
            </td>
          <% if current_user_is_owner %>
              <td><%= link_to '<i class="fa fa-fw fa-times"></i>'.html_safe, activity_path(activity),
                              method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
      <% end %>
    </table>
  <% else %>
  <div class="panel-body"><small>There are currently no activities in this group.</small></div>
  <% end %>
  </table>
</div>

<%= link_to 'Back', groups_path %>