config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: :show

  resources :groups do
    member do
      get 'add_user'
      post 'store_user'
      delete 'remove_user'
    end

    resources :activities, only: :new
  end
  
  resources :activities do
    member do
      post 'vote'
      post 'definitive'
	  get 'search_photo'
	  post 'choose_photo'
	  post 'store_photo_url'
    end
  end

  match '/tweet' => 'twitter#tweet', via: :all

  root :to => 'home#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  validates :name, presence: true, length: { in: 3..30 }
  validates :location, presence: true, length: { in: 3..20 }
  validates :start_date, presence: true
  validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :description, presence: true, length: { in: 6..1000 }

  belongs_to :group
  has_and_belongs_to_many :voters, class_name: 'User', join_table: :votes, :dependent => :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  # Check URL below for Devise's helper methods for eg. authentication etc.
  # https://github.com/plataformatec/devise#controller-filters-and-helpers

  helper_method :current_user_is_group_owner
  helper_method :get_group_name
  helper_method :has_voted

  before_filter :require_owner, only: [:new, :edit, :destroy, :mark_as_definitive]
  
  def index
	  @activities = Activity.all
  end

  def show
	  @activity = Activity.find(params[:id])
  end

  def destroy
    @activity = Activity.find(params[:id])
    group = Group.find(@activity.group_id)
    @activity.destroy
    redirect_to group
  end

  def new

    @group = Group.find(params[:group_id])
	  @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      @group = Group.find(@activity.group_id)
      redirect_to @group
    else
      @group = Group.find(params[:activity][:group_id])
      render action: 'new'
    end
  end

  def edit
	  @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update(activity_params)
      redirect_to @activity
    else
      render 'edit'
    end
  end
  
  def current_user_is_group_owner
    group = Group.find(@activity.group_id)
    group.owner_id == current_user.id
  end
  
  def get_group_name
    group = Group.find(@activity.group_id)
    group.name
  end

  def vote
    activity = Activity.find(params[:id])
    unless activity.voters.include?(current_user) then
      if activity.group.user.include?(current_user)
        activity.voters << current_user
      end
    end
    redirect_to :back
  end
  
  def has_voted
	@activity.voters.include?(current_user)
  end

  def definitive
    activity = Activity.find(params[:id])
    activity.definitive = true
    activity.save

    oauth_confirm_url = 'http://127.0.0.1:3000/tweet'

    client = TwitterOAuth::Client.new(
      :consumer_key => 'CIQ2fv3akOOp9l68NjQWNR6TS',
      :consumer_secret => 'kzVMmg1B92hMQWTAmx2iA89KZ9qKLgDwoaxhIRVBY8rxI7v8Rp'
    )

    request_token = client.request_token(:oauth_callback => oauth_confirm_url)

    session[:twitter_token] = request_token.token
    session[:twitter_secret] = request_token.secret
    session[:activity_id] = activity.id

    redirect_to request_token.authorize_url
  end
  
  def choose_photo
    FlickRaw.api_key="adee5f2be32399176cae039f2dc0a61e"
    FlickRaw.shared_secret="a371ebc40a2ebbb9"
    results = flickr.photos.search(:tags => params[:query], :per_page => '10')
    photos = []
    results.each do |p|
      info = flickr.photos.getInfo(:photo_id => p.id)
      photos << FlickRaw.url(info)
    end
    render 'choose_photo', :locals => { :photos => photos }
  end
  
  def store_photo_url
    @activity = Activity.find(params[:id])
    @activity.update_attribute(:image, params[:url])
    redirect_to @activity
  end

  private

  def require_owner
    if params.has_key?(:id)
      @group = Activity.find(params[:id]).group
    elsif params.has_key?(:group_id)
       @group = Group.find(params[:group_id])
    end

    if current_user.id != @group.owner_id
      redirect_to @group, alert: "You do not have permission to perform this action"
    end
  end

  def activity_params
    params.require(:activity).permit(:name, :location, :start_date, :description, :group_id, :duration)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity, html: {'novalidate' => 'true'} do |f| %>

  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited
        this activity from being saved:</h2>
      <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :group_id, :value => params[:group_id] ? params[:group_id] : params[:activity][:group_id]%>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label( :duration,"Duration in hours:") %><br>
    <%= f.number_field :duration %>
  </p>

  <p>
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/activities/choose_photo.erb
<h1>Choose a photo</h1>
<%= form_tag(store_photo_url_activity_path, method: "post") do %>
<center>
<table>
	<% photos.each do |p| %>
		<tr>
			<td><%= radio_button_tag(:url, p) %></td>
			<td><%= label_tag(:url, image_tag(p)) %></td>
		</tr>
	<% end %>
</table>
<%= submit_tag("Submit") %>
</center>
<% end %>
<br/>
<%= link_to 'Back', :back %>

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>

<%= render 'form', :params=>{:group_id=>@activity.group_id}%>

<%= link_to 'Back', group_path(@activity.group_id) %>

app/views/activities/index.html.erb
<h1>Activities Index</h1>

app/views/activities/new.html.erb
<h1>Create an Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', group_path(@group) %>

app/views/activities/search_photo.erb
<h1>Find a photo in Flickr</h1>

<%= form_tag(choose_photo_activity_path, method: "post") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<br/>

<%= link_to 'Back', :back %>

app/views/activities/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="media">
      <img class="pull-left media-object" src="<%= @activity.image %>" alt="">
      <div class="media-body">
        <h4 class="media-heading">
          <%= @activity.name %> for <%= get_group_name %> members
        </h4>
        <%= @activity.description %>
		<br/>
		<%= link_to 'Change picture', search_photo_activity_path %>
      </div>
    </div>
  </div>
  <table class="table">
    <tr>
      <th>Time</th>
      <th>Duration</th>
      <th>Location</th>
      <th>Votes</th>
      <th>Definitive</th>
    </tr>
    <tr>
      <td><%= @activity.start_date.to_formatted_s(:short) %></td>
      <td><%= pluralize(@activity.duration, "hour")%></td>
      <td><%= @activity.location %></td>
      <td>
		<%= @activity.voters.count %>
    <% if @activity.group.user.include?(current_user) %>
      <% if has_voted %>
        <i class="fa fa-fw fa-thumbs-o-up" style="color: grey;"></i>
          <% else %>
        <%= link_to '<i fa fa-fw fa-thumbs-o-up"></i> +1'.html_safe, vote_activity_path(@activity), method: :post %>
      <% end %>
    <% end %>
	  </td>
      <td>
        <%= @activity.definitive ? 'Yes' : 'No'%>
        <% if current_user_is_group_owner && ! @activity.definitive%>
          <%= link_to '<i class="fa fa-fw fa-check"></i> Mark as definitive'.html_safe, definitive_activity_path(@activity), method: :post %>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="panel-footer">
    <%= link_to 'Back', group_path(@activity.group_id) %>
    <% if current_user_is_group_owner %>
      <p class="pull-right">
        <%= link_to 'Edit', edit_activity_path(@activity) %>
        <%= link_to 'Delete', activity_path(@activity),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
  </div>
</div>