config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: :show

  resources :groups do
    member do
      get 'add_user'
      post 'store_user'
      delete 'remove_user'
    end

    resources :activities, only: :new
  end
  
  resources :activities do
    member do
      post 'vote'
      post 'definitive'
	  get 'search_photo'
	  post 'choose_photo'
	  post 'store_photo_url'
    end
  end

  match '/tweet' => 'twitter#tweet', via: :all

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebengMeetupGroups</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-5">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
	  <% if user_signed_in? %>
		  <a class="navbar-brand" href="<%= user_path(current_user) %>">My Meetups</a>
		  <a class="navbar-brand" href="<%=groups_path %>">All Meetups</a>
	  <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-5">
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>
  </div>
</nav>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
    <%= yield %>
</div>

</body>
</html>